# -*- Makefile -*-

# © 2010 Intel Corporation
#
# This software and the related documents are Intel copyrighted materials, and
# your use of them is governed by the express license under which they were
# provided to you ("License"). Unless the License provides otherwise, you may
# not use, modify, copy, publish, distribute, disclose or transmit this software
# or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or
# implied warranties, other than those that are expressly stated in the License.

# Simics module makefile

EXTRA_MODULE_VPATH = firewire-bus:dml-lib

MODULE_CLASSES = TSB12LV26

SRC_FILES = TSB12LV26.dml
PYTHON_FILES = module_load.py

SIMICS_API := 6
THREAD_SAFE = yes

include $(MODULE_MAKEFILE)
