# -*- Makefile -*-

# © 2025 Intel Corporation
#
# This software and the related documents are Intel copyrighted materials, and
# your use of them is governed by the express license under which they were
# provided to you ("License"). Unless the License provides otherwise, you may
# not use, modify, copy, publish, distribute, disclose or transmit this software
# or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or
# implied warranties, other than those that are expressly stated in the License.

# This module has been fully converted to CMake and should be built from CMake.

# In order to make it build in the old GNU Make setup; this file provides a
# trampoline. The trampoline is generic and can be re-used; but this is a
# workaround/gap-filler until project has fully converted to a CMake driven
# flow.

include $(SIMICS_REPO_ROOT)/config/cmake-gnu-wrapper.mk
